Homework # 5
SherstianoyVolchara/QA_AT_playground pull request #1
Opened 2022-02-17 18:47 UTC by SherstianoyVolchara

1. added first and second classes 
2. added int variable and  method to second class
3. instantiation instance of the 2nd class in the 1st class

2022-02-17 18:53 UTC, taraskarpenko requested changes

2022-02-17 18:53 UTC, taraskarpenko commented on src/main/java/First.java
> +        System.out.println("~~~" + second.showNumber() + "~~~");
Примените пожалйста форматирование строк

2022-02-17 18:53 UTC, taraskarpenko commented on src/main/java/Second.java
> +        System.out.println("---" + number + "---");
Примените пожалйста форматирование строк

2022-02-17 19:52 UTC, SherstianoyVolchara commented on src/main/java/First.java
> +        System.out.println("~~~" + second.showNumber() + "~~~");
@taraskarpenko added

2022-02-17 19:52 UTC, SherstianoyVolchara commented on src/main/java/Second.java
> +        System.out.println("---" + number + "---");
@taraskarpenko added

2022-02-18 00:04 UTC, taraskarpenko approved these changes

2022-02-18 07:30 UTC, merged